### PR TITLE
Drag and drop

### PR DESCRIPTION
**Pull request by cbuchko**
Added drag and drop functionality to the calendar view. User should be able to freely pickup and drag calendar items to reschedule them.

### CODE REVIEW

**Review by AndrewPolanyi — APPROVED** [review]
Honestly so impressed how smooth it feels, I be dropping all over the place, editing is seemless too. Legendary PR!

Not a blocker but I am wondering if when you drag a course to a timeslot, the other day should also be changed to this timeslot. For example: im asking the question if the same course can start at 8 on monday, 10 on wednesday and 12 on friday, or are they required to start at same time each day?

**Comment by cbuchko** [comment]
> Honestly so impressed how smooth it feels, I be dropping all over the place, editing is seemless too. Legendary PR!
> 
> Not a blocker but I am wondering if when you drag a course to a timeslot, the other day should also be changed to this timeslot. For example: im asking the question if the same course can start at 8 on monday, 10 on wednesday and 12 on friday, or are they required to start at same time each day?

Honestly I was wondering this too and I ended up deciding that its fine to give Rich the freedom to have times be whatever he wants them to be. But this would also be an easy thing to change if we change our minds later.

**Review by Adamk8 — APPROVED** [review]
Awesome work Connor! one thing that you could look into is that you get a different modal when you double click a course than when you do the edit button, this is not urgent (or needed to be done at all at this point lol)

**Review by nicudy — APPROVED** [review]
Looks great!

**Comment by cbuchko** [comment]
> Awesome work Connor! one thing that you could look into is that you get a different modal when you double click a course than when you do the edit button, this is not urgent (or needed to be done at all at this point lol)

This was a one line fix so I did it lol

**Pull request merged**
