### PR TITLE
Create sample survey results page with dummy data

### PR DESCRIPTION
**Pull request by Adamk8**
Created a table with all the fields related to the survey result spreadsheet that got posted in the general slack channel, included a button that will be used to reopen the survey in the future

image

### CODE REVIEW

**Comment by jayden-chan** [comment]
I think with real data this will probably end up being too much to try to display in one row of a table. We might want to just display one or two of the fields in the table and have the admin be able to expand it into either a modal or another page. Also I haven't looked at the data in detail but it seems like some of these columns are optional (like the topics courses stuff) so that might not be worth putting in the table.

**Comment by Adamk8** [comment]
> I think with real data this will probably end up being too much to try to display in one row of a table. We might want to just display one or two of the fields in the table and have the admin be able to expand it into either a modal or another page. Also I haven't looked at the data in detail but it seems like some of these columns are optional (like the topics courses stuff) so that might not be worth putting in the table.

Yeah the table is really busy, I'll see what I can do to make it more readable

**Comment by Adamk8** [comment]
I changed it so that the table is a bit simpler with a more details button to open a modal, once we have real data we may want to move things in or out of the modal but this should be good for now

**Review by jayden-chan — APPROVED** [review]
Nice, I checked out your branch locally and the new table and modal looks awesome :+1:

**Comment by nicudy** [comment]
Looks great!

**Review by nicudy — APPROVED** [review]

**Pull request merged**
