### PR TITLE
Add Prettier CI action

### PR DESCRIPTION
**Pull request by jayden-chan**
Adding Prettier CI pipeline

### CODE REVIEW

**Comment by jayden-chan** [comment]
This might take a minute to debug lol, don't approve it yet. But I need to open the PR for it to trigger the action so I can test it

**Comment by jayden-chan** [comment]
Alright looks like the action is working :+1:

**Review by cbuchko — APPROVED** [review]
blessed

**Review by nicudy — APPROVED** [review]
This is super helpful, thanks!

**Pull request merged**
