### PR TITLE
feat: Update generate page

### LINKED ISSUE #138: generation page course defaults and support generation per year
make it so that all courses for a term are selected on default. 
can uncheck courses

form will always have all semesters available, 3 course inputs instead of 1

### LINKED ISSUE #142: Change generation input
change generation input to look like:

### PR DESCRIPTION
**Pull request by jayden-chan**

### CODE REVIEW

**Comment by jayden-chan** [comment]
Opening this for review now because I think it's pretty much in the final state it's going to be in. I still can't generate a whole year schedule due to Algorithm 1 failing but I don't think there will be drastic changes once that's fixed

**Review by Adamk8 — COMMENTED** [review]
when selecting a whole year, the course list is quite long I wonder if theres a easy way to make this box scrollable:
image

Other than that its looking good

**Review by Adamk8 — COMMENTED** [review]
I checked into making the course lists scrollable and it seems to work if you put a chakra Box around the Table component, with CSS like: `                <Box
                  overflowY="auto"
                  __css={{
                    "&::-webkit-scrollbar": {
                      w: "2",
                    },
                    "&::-webkit-scrollbar-track": {
                      w: "6",
                    },
                    "&::-webkit-scrollbar-thumb": {
                      borderRadius: "10",
                      bg: `blue.200`,
                    },
                  }}
                  maxH="800px"
                >`
If you know of a better way that works too

**Comment by jayden-chan** [comment]
> I checked into making the course lists scrollable and it seems to work if you put a chakra Box around the Table component, with CSS like: ` <Box overflowY="auto" __css={{ "&::-webkit-scrollbar": { w: "2", }, "&::-webkit-scrollbar-track": { w: "6", }, "&::-webkit-scrollbar-thumb": { borderRadius: "10", bg:`blue.200`, }, }} maxH="800px" >` If you know of a better way that works too

I updated it to scroll, we don't need all that other CSS junk in there though, that's what Chakra handles for us :smiley:

**Review by Adamk8 — APPROVED** [review]

**Review by nicudy — APPROVED** [review]

**Comment by jayden-chan** [comment]
Looks like I am now able to generate a schedule using the "whole year" option with all courses selected. Going to merge this assuming it's correct and any issues would be on backend or algorithms from this point forward.

**Pull request merged**
