### PR TITLE
Global styling

### PR DESCRIPTION
**Pull request by AndrewPolanyi**
- Change headers to all be consistent and centered
- Changes button colorSchemes to be 'blue' unless it is a create or delete button
- Changed the nav bar to have uvic styling
- Change the dashboard to properly point to professors page

Let me know if you like the nav bar triple uvic color or not. I can change it back no problem, just thought it looked more unique!

image

image

### CODE REVIEW

**Review by nicudy — APPROVED** [review]
Nice, looks good!

**Review by Adamk8 — COMMENTED** [review]
Lookin good, if we want to be consistent across the board you could change the "Create User" button to blue on the Professors page and the Submit button to blue on the Preferences Survey. Other than that I like it

**Review by Adamk8 — COMMENTED** [review]
Still seeing this one as green but the rest are good 
image

**Comment by AndrewPolanyi** [comment]
I changed the remaining green create buttons to blue. I originally left them because i thought it might be okay fro the create ones to be green, bu i agree it is more consistent for them to be blue

**Comment by Adamk8** [comment]
> I changed the remaining green create buttons to blue. I originally left them because i thought it might be okay fro the create ones to be green, bu i agree it is more consistent for them to be blue

Oh I see, up to you, in my opinion I like them all blue

**Review by Adamk8 — APPROVED** [review]

**Pull request merged**
