### PR TITLE
Combined survey results and profile management

### PR DESCRIPTION
**Pull request by Adamk8**
Removed the survey results page and combined it into profile management page that I renamed to just "Professors"
If we decide to do editing or deletion we can update this page now 
image

### CODE REVIEW

**Comment by jayden-chan** [comment]
I tried running it locally and I am getting many errors
image
image

And the screen is just blank. Not sure if this is an issue with the backend proxy on my end or something but probably at the very least we would want a bit more graceful error handling

**Comment by jayden-chan** [comment]
Yeah it looks like the issue was caused by a stale login cookie in my browser. So I think things work in the happy path but we should probably implement a bit more robust error handling for if the data comes back null

**Comment by Adamk8** [comment]
> Yeah it looks like the issue was caused by a stale login cookie in my browser. So I think things work in the happy path but we should probably implement a bit more robust error handling for if the data comes back null

My bad, I updated the error handling and the other errors

**Review by jayden-chan — APPROVED** [review]

**Review by nicudy — APPROVED** [review]
Looks great, Adam!

**Pull request merged**
