### PR TITLE
#25 Nav Header Component

### LINKED ISSUE #25: Navigation header
Header that is persistent for all pages.
Allows for logout or navigation back to the dashboard.
Logout navigates back to the sign in page

### PR DESCRIPTION
**Pull request by jayden-chan**
This pull request implements the header bar (#25) which is always visible at the top of the application. It includes links to various parts of the application, and changes depending on whether the user is logged in or not (and if they are an admin)

The header bar is currently hooked into the global login store, so it's aware of the login state (although we can't actually log in yet because we're not hooked up to the backend)

### CODE REVIEW

**Comment by jayden-chan** [comment]
image

**Review by Adamk8 — APPROVED** [review]
In the future we will probably want to hide some parts of the header until the user is logged on but we can't do that yet. good work

**Comment by jayden-chan** [comment]
> In the future we will probably want to hide some parts of the header until the user is logged on but we can't do that yet. good work

@Adamk8 I already have the code necessary for doing that, just wasn't sure which pages we want to show or hide. If we know what we want to show in the not logged in / logged in / admin cases I can implement that now actually

**Comment by Adamk8** [comment]
> @Adamk8 I already have the code necessary for doing that, just wasn't sure which pages we want to show or hide. If we know what we want to show in the not logged in / logged in / admin cases I can implement that now actually

We can just make another issue for it later when we specify what is show to each user and have access to the backend, don't worry about it for now

**Review by AndrewPolanyi — APPROVED** [review]
looks great!

**Pull request merged**
