### PR TITLE
Prep for demo on monday

### LINKED ISSUE #73: End to End test of communication between frontend and backend
This is going to involve testing the NGINX config in the docker container to ensure that everything is set up correctly with the cookies and things.

### PR DESCRIPTION
**Pull request by jayden-chan**
Several updates needed for the demo on Monday:
* NGINX config uses environment variable to specify backend URL (thanks Adam for this suggestion)
* Login state management uses Zustand so components update properly
* Fix background color on the Generate Schedule page when light mode is on

I have also tested and verified that the NGINX reverse proxy to the backend is working locally. We can't test whether this works on 
Heroku until this PR is deployed and the backend is also up to date, so it's still just fingers crossed on that part.

Closes #73

### CODE REVIEW

**Review by AndrewPolanyi — APPROVED** [review]
Looks great to me, I like the gray footer text

**Review by Adamk8 — APPROVED** [review]
The code makes sense, I can't get the backend up anymore since they updated main so I couldn't test it but I trust that its working as intended

**Comment by jayden-chan** [comment]
> The code makes sense, I can't get the backend up anymore since they updated main so I couldn't test it but I trust that its working as intended

Yeah it was very broken for me as well, I just nuked the DB and followed the instructions in the README though and it works

**Comment by jayden-chan** [comment]
Going to merge this and give it a test now that the backend is deployed on Heroku. We may need to create and merge more PRs for this ticket in the future since the only way to test if it's working is to merge and deploy to Heroku lol

**Pull request merged**
