### PR TITLE
Remove package-lock.json for heroku deployment

### PR DESCRIPTION
**Pull request by Adamk8**
I'm working to get our app hosted on heroku, it doesn't like having both a yarn.lock and a package-lock.json so I removed package-lock.json.

In future commits don't include package-lock.json if you used npm to run the app

### CODE REVIEW

**Review by cbuchko — DISMISSED** [review]
good call

might be worth adding package-lock.json to the .gitignore?

**Review by cbuchko — COMMENTED** [review]
Could you resolve some of the warnings introduced in the User Management PR with this PR? 
Just some unused variables that are being imported.

**Comment by Adamk8** [comment]
> 

My bad, completely missed those cause of the other warnings from devextreme lol

**Comment by cbuchko** [comment]
yeah those devextreme ones are gross, if you look at the .env.example I put instructions on how to ignore them

**Review by cbuchko — DISMISSED** [review]

**Review by jayden-chan — DISMISSED** [review]
Yep, we should be using `yarn` for managing dependencies and running the app. There are instructions in the readme :+1:

**Review by jayden-chan — APPROVED** [review]

**Review by cbuchko — APPROVED** [review]

**Review by nicudy — APPROVED** [review]
Damn, that's nice!

**Pull request merged**
